INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '좋은 정보 감사합니다!', TO_DATE('2025-03-01', 'YYYY-MM-DD'), 39, 31);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '이해가 잘 됐어요.', TO_DATE('2025-03-02', 'YYYY-MM-DD'), 40, 32);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '질문이 있어요!', TO_DATE('2025-03-03', 'YYYY-MM-DD'), 41, 33);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '자료 감사합니다.', TO_DATE('2025-03-04', 'YYYY-MM-DD'), 42, 34);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '출석 체크 어떻게 하나요?', TO_DATE('2025-03-05', 'YYYY-MM-DD'), 43, 35);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '과제 제출일은 언제인가요?', TO_DATE('2025-03-06', 'YYYY-MM-DD'), 44, 36);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '공지 잘 봤습니다.', TO_DATE('2025-03-07', 'YYYY-MM-DD'), 45, 37);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '감사합니다!', TO_DATE('2025-03-08', 'YYYY-MM-DD'), 46, 38);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '시험 범위는 어디까지인가요?', TO_DATE('2025-03-09', 'YYYY-MM-DD'), 47, 39);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '열심히 하겠습니다!', TO_DATE('2025-03-10', 'YYYY-MM-DD'), 48, 40);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '좋은 정보 감사합니다.', TO_DATE('2025-03-11', 'YYYY-MM-DD'), 71, 44);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-03-12', 'YYYY-MM-DD'), 63, 51);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '친절한 설명 감사합니다.', TO_DATE('2025-03-13', 'YYYY-MM-DD'), 63, 53);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-03-14', 'YYYY-MM-DD'), 53, 39);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '수업 자료 부탁드립니다.', TO_DATE('2025-03-15', 'YYYY-MM-DD'), 49, 38);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '좋은 정보 감사합니다.', TO_DATE('2025-03-16', 'YYYY-MM-DD'), 74, 40);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-03-17', 'YYYY-MM-DD'), 85, 32);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '수업 자료 부탁드립니다.', TO_DATE('2025-03-18', 'YYYY-MM-DD'), 49, 51);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '강의 자료 공유해주세요!', TO_DATE('2025-03-19', 'YYYY-MM-DD'), 45, 38);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '수업 자료 부탁드립니다.', TO_DATE('2025-03-20', 'YYYY-MM-DD'), 54, 41);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '친절한 설명 감사합니다.', TO_DATE('2025-03-21', 'YYYY-MM-DD'), 86, 46);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '수업 자료 부탁드립니다.', TO_DATE('2025-03-22', 'YYYY-MM-DD'), 83, 59);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '좋은 정보 감사합니다.', TO_DATE('2025-03-23', 'YYYY-MM-DD'), 53, 55);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '이번 시험 화이팅!', TO_DATE('2025-03-24', 'YYYY-MM-DD'), 67, 45);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '오늘도 수고 많으셨습니다.', TO_DATE('2025-03-25', 'YYYY-MM-DD'), 48, 55);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '오늘도 수고 많으셨습니다.', TO_DATE('2025-03-26', 'YYYY-MM-DD'), 44, 35);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '다시 한번 공지해주세요!', TO_DATE('2025-03-27', 'YYYY-MM-DD'), 42, 56);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '빠른 공지 감사합니다.', TO_DATE('2025-03-28', 'YYYY-MM-DD'), 52, 58);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '이번 시험 화이팅!', TO_DATE('2025-03-29', 'YYYY-MM-DD'), 69, 52);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-03-30', 'YYYY-MM-DD'), 62, 51);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '친절한 설명 감사합니다.', TO_DATE('2025-03-31', 'YYYY-MM-DD'), 86, 44);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-04-01', 'YYYY-MM-DD'), 45, 39);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-04-02', 'YYYY-MM-DD'), 81, 43);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '친절한 설명 감사합니다.', TO_DATE('2025-04-03', 'YYYY-MM-DD'), 46, 57);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '확인했습니다.', TO_DATE('2025-04-04', 'YYYY-MM-DD'), 70, 45);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '좋은 정보 감사합니다.', TO_DATE('2025-04-05', 'YYYY-MM-DD'), 44, 55);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '오늘도 수고 많으셨습니다.', TO_DATE('2025-04-06', 'YYYY-MM-DD'), 54, 37);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '빠른 공지 감사합니다.', TO_DATE('2025-04-07', 'YYYY-MM-DD'), 56, 31);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '이번 시험 화이팅!', TO_DATE('2025-04-08', 'YYYY-MM-DD'), 63, 38);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '강의 자료 공유해주세요!', TO_DATE('2025-04-09', 'YYYY-MM-DD'), 45, 43);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '친절한 설명 감사합니다.', TO_DATE('2025-04-10', 'YYYY-MM-DD'), 53, 47);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '강의 자료 공유해주세요!', TO_DATE('2025-04-11', 'YYYY-MM-DD'), 58, 53);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '확인했습니다.', TO_DATE('2025-04-12', 'YYYY-MM-DD'), 60, 45);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-04-13', 'YYYY-MM-DD'), 87, 31);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-04-14', 'YYYY-MM-DD'), 48, 55);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '잘 이해가 안돼요 ㅠㅠ', TO_DATE('2025-04-15', 'YYYY-MM-DD'), 80, 55);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '다시 한번 공지해주세요!', TO_DATE('2025-04-16', 'YYYY-MM-DD'), 53, 43);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '다시 한번 공지해주세요!', TO_DATE('2025-04-17', 'YYYY-MM-DD'), 41, 35);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '다시 한번 공지해주세요!', TO_DATE('2025-04-18', 'YYYY-MM-DD'), 78, 48);

INSERT INTO TB_REPLY (REPLY_NO, CONTENT, CREATE_DATE, USER_NO, BOARD_NO) VALUES (SEQ_REPLY_NO.NEXTVAL, '다시 한번 공지해주세요!', TO_DATE('2025-04-19', 'YYYY-MM-DD'), 60, 44);


