INSERT INTO TB_RESUME_BOARD (RESUME_NO, USER_NO, TYPE, TITLE, FILE_PATH, CREATED_DATE, UPDATE_DATE) VALUES (SEQ_RESUME_NO.NEXTVAL, 8, 1, '2025 상반기 자기소개서', '/resumes/resume_1.pdf', '2025-03-27', NULL);
INSERT INTO TB_RESUME_BOARD (RESUME_NO, USER_NO, TYPE, TITLE, FILE_PATH, CREATED_DATE, UPDATE_DATE) VALUES (SEQ_RESUME_NO.NEXTVAL, 3, 1, '풀스택 자소서', '/resumes/resume_2.pdf', '2025-03-27', NULL);
INSERT INTO TB_RESUME_BOARD (RESUME_NO, USER_NO, TYPE, TITLE, FILE_PATH, CREATED_DATE, UPDATE_DATE) VALUES (SEQ_RESUME_NO.NEXTVAL, 10, 2, '회사 제출용 이력서', '/resumes/resume_3.pdf', '2025-03-23', NULL);
